dist: trusty

sudo: required

notifications:
  email: false

language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - sudo apt-get install build-essential

install:
  - make install

script:
  - make build
