dist: trusty

sudo: required

branches:
  except:
  - gh-pages

notifications:
  email: false

language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - sudo apt-get install --assume-yes --quiet build-essential
  - npm i -g codecov

install:
  - cd scripts && npm ci && cd ..
  - make install

script:
  - make build
  - make test && codecov

after_success:
  - npm i -g jsdoc
  - make docs

deploy:
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy Production
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
env:
  # DEPLOY_SETTINGS_JSON='{"Production":[
  #   {"type":"docker","options":{"source":"zevere/calista","target":"zevere/chatbot-calista","user":"","pass":""}},
  #   {"type":"heroku","options":{"app":"zv-chatbot-calista","source":"zevere/chatbot-calista","dyno":"web","user":"","token":""}}
  # ]}'
  - secure: t37zlN8sEy9Ljzm3CCQeN7Cmv8+ctmjKpzDVnlbUYYhFNi5NMBZ0MoqKq53gcvyNU9wuPPJHI1E20WtWx5SJiR4lUs9squ4/KnH6ITpLVad89X3lXhmagCS5DWvUiDww4l3HXVuKO9yyykBrMhbxo0M2INApC30Mkk8+4OrYagOpsEneh0hNXV1Vk3Asn9OnrmdQD/CZR0ZRf7v8RRGCkUOCVCurJlaOUwm8cqbRy02pav1i32cm6izahmeNfdGImjGlSyptMMq1KlaSjb6Y38tTtknX6cgsoRC5x3I4JTcWP1cuaHhsM+sBnBN52LGt1Ib265SB+a8l1w9vA9gUges4RZEA/wgbqlQUkwz2YuFrm0xnmASXM6WnrF+t87bGXxPvAXA6BifyfvzXb6o4DoB1+75Uq53mePo8XrbRvof4v2HR26fbZUOchhIwrVQzm9TsoXGES1P9lHBY93KxMu2oOds1HXM/E1r7CETNTX6b/99TSS9kAZaaP/ve2mdg2xEGq0x4+IRchd6pdGDKam5zXpgvAlWZeW9MPKvPXWQ5hqkWCMWN5AE9ImTjhmUEfyZEceQ8uZGzyB0Wvwp5GJ2n/iJQwARkkAEyJyANaWRRDS7JYu73R1jnj6jmlAuPJL0jicCMJfnTvhCeOeqkQJvs9vtsOETJgWjnwIwf1hI=


# Disable "Build pushed pull requests"
