dist: trusty

sudo: required

branches:
  only:
  - master

notifications:
  email: false

language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install snapd

install:
  - make install

script:
  - make build

after_success:
  - npm i -g codecov
  - codecov

deploy:
  provider: script
  script: make deploy
  on:
    branch: master